# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  electionnet:

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=./channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer.ec.ug/msp
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer.ec.ug/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer.ec.ug/tls/server.cert
      # - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/msp/orderer0.ec.ug/tls/ca.crt
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /usr/local/bin
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/ec.ug/orderers:/etc/hyperledger/msp
      - ./channel-artifacts/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"

  peer:
    container_name: peer
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=BallotMachinesMSP
      - CORE_PEER_LOCALMSPDIR=/etc/hyperledger/msp/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=
      - CORE_PEER_TLS_KEY_FILE=
      - CORE_PEER_TLS_ROOTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peers/peer.BallotMachines.ec.ug/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer
      - couchdb

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peers/cli.BallotMachines.ec.ug/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './script.sh'
    ports:
      - 7056:7056
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
        - ./chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/
    depends_on:
      - orderer
      - peer

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peers/chaincode.BallotMachines.ec.ug/msp
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    ports:
      - 7055:7055
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
        - ./chaincode:/opt/gopath/src/chaincode
    depends_on:
      - orderer
      - peer
