# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  electionnet:

services:
  ca:
    container_name: ca.BallotMachines.ec.ug
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.BallotMachines.ec.ug-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7dfce585b0f3b602b2f186985e3ab03de734702a8153d861679207b3d57dd1c8_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.BallotMachines.ec.ug-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7dfce585b0f3b602b2f186985e3ab03de734702a8153d861679207b3d57dd1c8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/ca:/etc/hyperledger/fabric-ca-server-config
    networks:
      - electionnet

  orderer:
    container_name: orderer.ec.ug
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/fabric/channel-artifacts/genesis.block
      # - ORDERER_GENERAL_GENESISPROFILE=BallotMachinesMSP
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /usr/local/bin
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/ec.ug/orderers/orderer.ec.ug/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer0.BallotMachines.ec.ug/:/etc/hyperledger/msp/BallotMachines
      - ./channel-artifacts/:/etc/hyperledger/fabric/channel-artifacts
      - ./channel-artifacts/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050
    networks:
      - electionnet

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"
    networks:
      - electionnet

  peer0:
    container_name: peer0.BallotMachines.ec.ug
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.BallotMachines.ec.ug
      - CORE_PEER_ADDRESS=peer0.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.BallotMachines.ec.ug:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer0.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer0.BallotMachines.ec.ug/msp/:/etc/hyperledger/fabric/msp
      # - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/users/:/etc/hyperledger/msp/users
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - electionnet
    depends_on:
      - orderer
      - couchdb0
    
  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    ports:
      - "6984:5984"
    networks:
      - electionnet

  peer1:
    container_name: peer1.BallotMachines.ec.ug
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.BallotMachines.ec.ug
      - CORE_PEER_ADDRESS=peer1.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.BallotMachines.ec.ug:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer1.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer1.BallotMachines.ec.ug/msp/:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - electionnet
    depends_on:
      - orderer
      - couchdb1
  
  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    ports:
      - "7984:5984"
    networks:
      - electionnet

  peer2:
    container_name: peer2.BallotMachines.ec.ug
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.BallotMachines.ec.ug
      - CORE_PEER_ADDRESS=peer2.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.BallotMachines.ec.ug:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer2.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer2.BallotMachines.ec.ug/msp/:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - electionnet
    depends_on:
      - orderer
      - couchdb2
    
  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    ports:
      - "8984:5984"
    networks:
      - electionnet

  peer3:
    container_name: peer3.BallotMachines.ec.ug
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.BallotMachines.ec.ug
      - CORE_PEER_ADDRESS=peer3.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.BallotMachines.ec.ug:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer3.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer3.BallotMachines.ec.ug/msp/:/etc/hyperledger/fabric/msp
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - electionnet
    depends_on:
      - orderer
      - couchdb3

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    ports:
      - "9984:5984"
    networks:
      - electionnet

  peer4:
    container_name: peer4.BallotMachines.ec.ug
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.BallotMachines.ec.ug
      - CORE_PEER_ADDRESS=peer4.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.BallotMachines.ec.ug:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer4.BallotMachines.ec.ug:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_PEER_TLS_CLIENTAUTHREQUIRED=
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=
      # - CORE_PEER_TLS_CLIENTCERT_FILE=
      # - CORE_PEER_TLS_CLIENTKEY_FILE=
      # - CORE_PEER_MSPCONFIGPATH/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
    volumes:
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer4.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer4.BallotMachines.ec.ug/msp/:/etc/hyperledger/fabric/msp
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - electionnet
    depends_on:
      - orderer
      - couchdb4

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.BallotMachines.ec.ug:7051
      - CORE_PEER_LOCALMSPID=BallotMachinesMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peers/peer0.BallotMachines.ec.ug/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peers/peer0.BallotMachines.ec.ug/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peers/peer0.BallotMachines.ec.ug/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@BallotMachines.ec.ug/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './script.sh'
    ports:
      - 7056:7056
    networks:
      - electionnet
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
        - ./crypto-config/ordererOrganizations/ec.ug/:/etc/hyperledger/msp/orderer
        - ./chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/
        - ./channel-artifacts:/opt/gopath/src/chaincodedev/channel-artifacts
        - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/peers/peer0.BallotMachines.ec.ug/tls/:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer
      - peer0
      - peer1
      - peer2
      - peer3
      - peer4

  # chaincode:
  #   container_name: chaincode
  #   image: hyperledger/fabric-ccenv
  #   tty: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_ID=chaincode
  #     - CORE_PEER_ADDRESS=peer0.BallotMachines.ec.ug:7051
  #     - CORE_PEER_LOCALMSPID=DEFAULT
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peers/chaincode.BallotMachines.ec.ug/msp
  #   working_dir: /opt/gopath/src/chaincode
  #   command: /bin/bash -c 'sleep 6000000'
  #   ports:
  #     - 7055:7055
  #   networks:
  #     - electionnet   
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ./crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
  #       - ./chaincode:/opt/gopath/src/chaincode
  #   depends_on:
  #     - orderer
  #     - peer
