# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_LOCALMSPID=BallotMachinesMSP
      - CORE_PEER_LOCALMSPDIR=/etc/hyperledger/msp/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_PEER=debug
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/BallotMachines.ec.ug/:/etc/hyperledger/msp
      - ../crypto-config/ordererOrganizations/ec.ug/:/etc/hyperledger/msp/orderer
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './join-channel.sh' 